import { useState, useEffect, useCallback } from 'react';
import { notificationService } from '../services/notification.service';

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/\-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function usePushNotifications() {
  const [isSupported, setIsSupported] = useState(false);
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [permission, setPermission] = useState<NotificationPermission>('default');
  const [loading, setLoading] = useState(true);

  // Check if push notifications are supported and retrieve existing subscription
  const checkSupportAndSubscription = useCallback(async () => {
    const supported =
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window;

    setIsSupported(supported);

    if (supported) {
      setPermission(Notification.permission);
      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await registration.pushManager.getSubscription();
        setIsSubscribed(!!subscription);
      } catch (err) {
        console.error('Error checking push subscription status:', err);
      }
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    checkSupportAndSubscription();
  }, [checkSupportAndSubscription]);

  // Subscribe user to push notifications
  const subscribe = async () => {
    if (!isSupported) return false;

    setLoading(true);
    try {
      // 1. Request permission
      const userPermission = await Notification.requestPermission();
      setPermission(userPermission);

      if (userPermission !== 'granted') {
        setLoading(false);
        return false;
      }

      // 2. Register/Wait for service worker to be ready
      // Ensure service worker is registered first
      let registration = await navigator.serviceWorker.getRegistration();
      if (!registration) {
        registration = await navigator.serviceWorker.register('/sw.js');
      }
      await navigator.serviceWorker.ready;

      // 3. Get VAPID public key from backend or env
      let vapidPublicKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
      try {
        const res = await notificationService.getPushPublicKey();
        if (res.publicKey) {
          vapidPublicKey = res.publicKey;
        }
      } catch (keyErr) {
        console.warn('Failed to retrieve VAPID key from backend, using env fallback:', keyErr);
      }

      if (!vapidPublicKey || vapidPublicKey === 'your-public-key') {
        throw new Error('VAPID public key is not configured.');
      }

      const applicationServerKey = urlBase64ToUint8Array(vapidPublicKey);

      // 4. Subscribe with the push manager
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });

      // 5. Save subscription details on the backend
      const subscriptionJson = subscription.toJSON();
      if (!subscriptionJson.endpoint || !subscriptionJson.keys?.auth || !subscriptionJson.keys?.p256dh) {
        throw new Error('Invalid subscription payload generated by the browser.');
      }

      await notificationService.subscribePush({
        endpoint: subscriptionJson.endpoint,
        keys: {
          auth: subscriptionJson.keys.auth,
          p256dh: subscriptionJson.keys.p256dh,
        },
      });

      setIsSubscribed(true);
      setLoading(false);
      return true;
    } catch (err) {
      console.error('Failed to subscribe to push notifications:', err);
      setLoading(false);
      throw err;
    }
  };

  // Unsubscribe user from push notifications
  const unsubscribe = async () => {
    if (!isSupported) return false;

    setLoading(true);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();

      if (subscription) {
        // 1. Notify backend to clean up subscription
        await notificationService.unsubscribePush(subscription.endpoint);

        // 2. Unsubscribe browser-side
        await subscription.unsubscribe();
      }

      setIsSubscribed(false);
      setLoading(false);
      return true;
    } catch (err) {
      console.error('Failed to unsubscribe from push notifications:', err);
      setLoading(false);
      return false;
    }
  };

  return {
    isSupported,
    isSubscribed,
    permission,
    loading,
    subscribe,
    unsubscribe,
  };
}
